
services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=pp_portal_db
      - DB_PORT=5432
      - JWT_SECRET=your_secure_jwt_secret_here
      - DB_CONNECTION_STRING=postgres://postgres:1234@db:5432/pp_portal_db
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: pp-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: pp_portal_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # optional, remove if DB should be internal only
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pp_portal_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
    driver: local
